services:
  registry:
    restart: always
    build:
      context: .
      dockerfile: registry/Dockerfile
    ports:
      - "8002:8001"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    environment:
      - CONFIG_PATH=/app/config.yaml

  engine:
    restart: always
    build:
      context: .
      dockerfile: engine/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_PATH=/app/config.yaml
      - FORGE_INTERNAL_TOKEN=test-token
      - HOST_DATA_PATH=${PWD}/data
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    depends_on:
      - registry
